# Generated by Django 5.1.4 on 2024-12-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicles_adr'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFullDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_chock', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Нe')),
                ('two_warning_signs', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('eye_wash_liquid', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('reflective_vest', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('portable_lighting_fixture', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('a_pair_of_protective_gloves', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('eye_protection', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('mask', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('shovel', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('manhole_cover', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('collection_container', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('written_instructions_colored', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('fire_extinguishers', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не')),
                ('insurance_civil_liability', models.DateField(blank=True, null=True)),
                ('insurance_casco_validity', models.DateField(blank=True, null=True)),
                ('tachograph_validity', models.DateField(blank=True, null=True)),
                ('adr_validity', models.DateField(blank=True, null=True)),
                ('fitness_protocol_validity', models.DateField(blank=True, null=True)),
                ('technical_check_validity', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
