# Generated by Django 5.1.4 on 2024-12-17 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('brand', models.CharField()),
                ('model', models.CharField()),
                ('register_number', models.CharField(validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(8)])),
                ('condition', models.TextField(validators=[django.core.validators.MaxLengthValidator(50)])),
            ],
        ),
    ]
