# Generated by Django 5.1.4 on 2024-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='type',
            field=models.CharField(choices=[('ВЛЕКАЧ', 'ВЛЕКАЧ'), ('ЦИСТЕРНА', 'ЦИСТЕРНА'), ('АВТОМОБИЛ', 'АВТОМОБИЛ')], default='АВТОМОБИЛ'),
        ),
    ]
