# Generated by Django 5.1.4 on 2024-12-20 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vehiclefulldetails_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='register_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
