# Generated by Django 5.1.4 on 2024-12-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vehicles_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='adr',
            field=models.CharField(choices=[('Yes', 'Да'), ('No', 'Не')], default='Да'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='condition',
            field=models.CharField(choices=[('aktiven', 'АКТИВЕН'), ('v_remont', 'В РЕМОНТ')], default='АКТИВЕН', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='type',
            field=models.CharField(choices=[('vlekach', 'ВЛЕКАЧ'), ('cisterne', 'ЦИСТЕРНА'), ('avtomobil', 'АВТОМОБИЛ')], default='АВТОМОБИЛ'),
        ),
    ]
