# Generated by Django 5.1.4 on 2024-12-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vehicles_adr_alter_vehicles_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='adr',
            field=models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Да'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='condition',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В РЕМОНТ', 'В РЕМОНТ')], default='АКТИВЕН', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='type',
            field=models.CharField(choices=[('ВЛЕКАЧ', 'ВЛЕКАЧ'), ('ЦИСТЕРНА', 'ЦИСТЕРНА'), ('АВТОМОБИЛ', 'АВТОМОБИЛ')], default='АВТОМОБИЛ'),
        ),
    ]
