# Generated by Django 5.1.4 on 2024-12-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_vehiclefulldetails_reflective_vest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefulldetails',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='full_details', to='accounts.vehicles'),
            preserve_default=False,
        ),
    ]
