# Generated by Django 5.1.4 on 2024-12-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_vehiclefulldetails_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefulldetails',
            name='reflective_vest',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Не', 'Не')], default='Не', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehiclefulldetails',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_details', to='accounts.vehicles'),
        ),
    ]
