# Generated by Django 5.1.2 on 2025-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_vehiclefulldetails_a_pair_of_protective_gloves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='comp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
